local self = {}

self.file_types = {
    settings = {
    ".json",
    ".txt",
    ".lua",
    ".luau"
    },
    imgs = { -- well idk about your executor but it should support these, if not. PLEASE tell me so i do shit about it
    ".png",
    ".jpeg",
    ".gif",
    ".tga",
    ".bmp"
    },
    sounds = {
".mp3",
    ".ogg",
    ".wav",
    ".flac"
    },
    video = { -- WHO the fuck uses this shit in roblox??? idk but yeah ig
    ".mp4",
    ".mov" -- "bc i use mac" only real ones remember this one
    },
}

return self